// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.19.4
// source: pay-server/v1/pay-service.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPayServiceDetail = "/pay_server.v1.PayService/Detail"
const OperationPayServicePay = "/pay_server.v1.PayService/Pay"

type PayServiceHTTPServer interface {
	Detail(context.Context, *DetailRequest) (*DetailResponse, error)
	Pay(context.Context, *PayRequest) (*PayResponse, error)
}

func RegisterPayServiceHTTPServer(s *http.Server, srv PayServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/pay", _PayService_Pay0_HTTP_Handler(srv))
	r.GET("/v1/pay/{order_id}", _PayService_Detail0_HTTP_Handler(srv))
}

func _PayService_Pay0_HTTP_Handler(srv PayServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PayRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPayServicePay)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Pay(ctx, req.(*PayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PayResponse)
		return ctx.Result(200, reply)
	}
}

func _PayService_Detail0_HTTP_Handler(srv PayServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPayServiceDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Detail(ctx, req.(*DetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DetailResponse)
		return ctx.Result(200, reply)
	}
}

type PayServiceHTTPClient interface {
	Detail(ctx context.Context, req *DetailRequest, opts ...http.CallOption) (rsp *DetailResponse, err error)
	Pay(ctx context.Context, req *PayRequest, opts ...http.CallOption) (rsp *PayResponse, err error)
}

type PayServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPayServiceHTTPClient(client *http.Client) PayServiceHTTPClient {
	return &PayServiceHTTPClientImpl{client}
}

func (c *PayServiceHTTPClientImpl) Detail(ctx context.Context, in *DetailRequest, opts ...http.CallOption) (*DetailResponse, error) {
	var out DetailResponse
	pattern := "/v1/pay/{order_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPayServiceDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *PayServiceHTTPClientImpl) Pay(ctx context.Context, in *PayRequest, opts ...http.CallOption) (*PayResponse, error) {
	var out PayResponse
	pattern := "/v1/pay"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPayServicePay))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
