// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package orderserver

import (
	"github.com/costa92/micros-service/internal/orderserver/server"
	"github.com/costa92/micros-service/internal/orderserver/service"
	"github.com/costa92/micros-service/internal/pkg/bootstrap"
	"github.com/costa92/micros-service/internal/pkg/metrics"
	"github.com/costa92/micros-service/pkg/db"
	"github.com/go-kratos/kratos/v2"
)

// Injectors from wire.go:

func wireApp(appInfo bootstrap.AppInfo, config *server.Config, mySQLOptions *db.MySQLOptions) (*kratos.App, func(), error) {
	logger := bootstrap.NewLogger(appInfo)
	appConfig := bootstrap.AppConfig{
		Info:   appInfo,
		Logger: logger,
	}
	metricsMetrics, err := metrics.InitMetrics(appInfo)
	if err != nil {
		return nil, nil, err
	}
	orderService := service.NewOrderService(metricsMetrics)
	v := server.NewMiddlewares(logger, metricsMetrics)
	httpServer := server.NewHTTPServer(config, orderService, v)
	grpcServer := server.NewGRPCServer(config, orderService, v)
	v2 := server.NewServers(httpServer, grpcServer)
	app := bootstrap.NewApp(appConfig, v2...)
	return app, func() {
	}, nil
}
