# Copyright 2024 costalong <costa9293@gmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/costa92/micros-service

# pay_server 服务配置文件
http:
  addr: ${ORDER_SERVER_HTTP_ADDR} # HTTP 服务监听地址

grpc:
  addr: ${ORDER_SERVER_GRPC_ADDR} # gRPC 服务监听地址

mysql:
  host: ${MYSQL_ADDR} # 数据库主机地址
  database: ${MYSQL_DATABASE} # 数据库名称
  username: ${MYSQL_USERNAME} # 数据库用户名
  password: ${MYSQL_PASSWORD} # 数据库密码
  log-level: ${MYSQL_LOG_LEVEL} # 数据库日志级别，1 为最低，4 为最高
